# Copyright (c) 2020-2021, RTE (https://www.rte-france.com)
# See AUTHORS.txt
# This Source Code Form is subject to the terms of the Mozilla Public License, version 2.0.
# If a copy of the Mozilla Public License, version 2.0 was not distributed with this file,
# you can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# This file is part of MILP_Agent, The MILP_Agent is a optimization based agent that manage the power flow
# overthermal using topological actions.


"""
Defines global variables to be imported in other python files
"""

THETA = "theta"
FLOW_B = "flow_b"
FLOW_B_PLUS = "flow_b_plus"
FLOW_B_MINUS = "flow_b_minus"
SLACK_N_PLUS = "slack_n_plus"
SLACK_N_MINUS = "slack_n_minus"
SLACK_B = "slack_b"
SWITCH_B = "switch_b"
PROD = "prod"

FMAX = "fmax"

LINES_OR_ID = "lines_or_id"
LINES_EX_ID = "lines_ex_id"
GENERATORS_ID = "generators_id"
LOADS_ID = "loads_id"
LOAD = "load"
GEN = "gen"
BUS = "bus"
LINE = "line"
FROM_BUS = "from_bus"
TO_BUS = "to_bus"
MAX_RAMP_UP = "max_ramp_up"
MAX_RAMP_DOWN = "max_ramp_down"
PMAX = "Pmax"
PMIN = "Pmin"
MIP = "mip"
MARGINAL_COST = "marginal_cost"

ZONE_BRANCH = "zone_branch"
ZONE_BUS = "zone_bus"
ZONE_PROD = "zone_prod"
ZONE_INTERIOR_BUS = "zone_interior_bus"
ZONE_BOUNDARY_BUS = "zone_boundary_bus"
ZONE_INTERIOR_PROD = "zone_interior_prod"
ZONE_BOUNDARY_PROD = "zone_boundary_prod"

DO_NOTHING = "do_nothing"
OBSERVATIONS = "observations.csv"
SOLUTIONS = "solutions.csv"
ACTIONS = "actions.csv"
SET_LINE_STATUS = "set_line_status"
CHANGE_LINE_STATUS = "change_line_status"
HAZARDS = "hazards"
MAINTENANCE = "maintenance"
REDISPATCH = "redispatch"
LOADS = "loads"
PRODS = "prods"
LINES_OR = "lines_or"
LINE_STATUS = "line_status"
TOPO_VECT = "topo_vect"
RHO = "rho"
DATA = "data"
OBSERVATIONS_NPZ = "observations.npz"
SOLUTIONS_NPZ = "solutions.npz"
ACTIONS_NPZ = "actions.npz"
INFO_NPZ = 'info.npz'
EXTRACTED = "extracted.csv"

OBJ = "objective"
MIP_XPRESS = "mip_xpress"
MIP_CBC = "mip_cbc"
MIP_SCIP = "scip"
MIP_GUROBI = "gurobi"
MIP_GLPK = "glpk"

RTE_CASE5_EXAMPLE = "rte_case5_example"
CONNECTED_ID = "connected_id"


TRAFO = "trafo"
LENGTH_KM = "length_km"
X_OHM_PER_KM = "x_ohm_per_km"
PARALLEL = "parallel"
TAP_NEUTRAL = "tap_neutral"
TAP_SIDE = "tap_side"
TAP_POS = "tap_pos"
TAP_STEP_PERCENT = "tap_step_percent"
VN_HV_KV = "vn_hv_kv"
VN_LV_KV = "vn_lv_kv"
VN_KV = "vn_kv"
LV_BUS = "lv_bus"
HV_BUS = "hv_bus"
HV = "hv"
VK_PERCENT = "vk_percent"
VKR_PERCENT = "vkr_percent"
SN_MVA = "sn_mva"
SHIFT_DEGREE = "shift_degree"
MAX_I_KA = "max_i_ka"

FILENAME_5 = "prods_charac5.csv"
FILENAME_118 = "prods_charac118.csv"
FILENAME_14 = "prods_charac14.csv"
TYPE = "type"
NAME = "name"
ZONE = "zone"
ZONE_LOAD = "zone_load"
ZONE_INTERIOR_LOAD = "zone_interior_load"
ZONE_BOUNDARY_LOAD = "zone_boundary_load"


CLUSTERING = "clustering.csv"
CLUSTER = "Cluster"
QUAD_NODE = "quad_node"
QUAD_FLOW = "quad_flow"
FLOW_B_MINUS_P_OR = "flow_b_minus_p_or"

ISOLVER_VARIABLE_LIST = [THETA, FLOW_B, FLOW_B_PLUS, FLOW_B_MINUS, SLACK_N_PLUS, SLACK_N_MINUS, SLACK_B, SWITCH_B, PROD,
                         QUAD_NODE, QUAD_FLOW, FLOW_B_MINUS_P_OR]

BUILDER_VARIABLE_LIST = [THETA, FLOW_B, FLOW_B_PLUS, FLOW_B_MINUS, SLACK_N_PLUS, SLACK_N_MINUS, SLACK_B, SWITCH_B, PROD]

BUILDER_CONSTRAINT_LIST = [THETA, FMAX, SLACK_B, SWITCH_B]

MIP_SCIP = "scip"
MIP_GUROBI = "gurobi"
MIP_GLPK = "glpk"

LINEAR_XPRESS = "linear_xpress"
LINEAR_GLOP = "linear_glop"
SOLVER_LIST = [MIP_XPRESS, LINEAR_GLOP, LINEAR_XPRESS]
STATE_ESTIMATION = "state_estimation"
V_OR = "v_or"
V_EX = "v_ex"
MAX_FLOW = "max_flow"
A_OR = "i_or"
A_EX = "i_ex"
P_OR = "p_or"
P_EX = "p_ex"
Q_OR = "q_or"
Q_EX = "q_ex"
CONSERVATIVE_LIMITS = "conservative_limits"
QUAD_STATE_ESTIMATION = "quad_state_estimation"
NODES_SPLIT = "nodes_split"
U1 = "_bus_1"
U2 = "_bus_2"
DELTA_THETA_B = "delta_theta_b"
ETA_OR = "eta_or"
ETA_EX = "eta_ex"
ETA_PROD = "eta_prod"
ETA_LOAD = "eta_load"
OR = "_or"
EX = "_ex"
ISOLVER_VARIABLE_LIST += [FLOW_B+U1+OR, FLOW_B+U1+EX, FLOW_B+U2+OR, FLOW_B+U2+EX, DELTA_THETA_B, ETA_OR, ETA_EX,
                          ETA_PROD, ETA_LOAD, SLACK_N_PLUS+U1, SLACK_N_PLUS+U2, SLACK_N_MINUS+U1, SLACK_N_MINUS+U2,
                          THETA+U1, THETA+U2, PROD+U1, PROD+U2, LOAD+U1, LOAD+U2]

TIME = "time"
ID_OBJECT = "id_object"
ATTRIBUTE = "attribute"
VALUE = "value"
BUS_OR = "bus_or"
BUS_EX = "bus_ex"

BUS_DEGREE = "bus_degree"
BUS_DEGREE_OR = "bus_degree_or"
BUS_DEGREE_EX = "bus_degree_ex"
X_BRANCH = "x_branch"
RES_LINE_KEY = ["p_from_mw", "q_from_mvar", "p_to_mw", "q_to_mvar", "i_from_ka", "i_to_ka", "vm_from_pu",
                "vm_to_pu", "va_from_degree", "va_to_degree"]
DOUBLE_OPTIM = "double_optim"
RES_TRAFO_KEY = ["p_hv_mw", "q_hv_mvar", "p_lv_mw", "q_lv_mvar", "i_hv_ka", "i_lv_ka", "vm_hv_pu", "vm_lv_pu",
                 "va_hv_degree", "va_lv_degree"]
DELTA_FLOW = "delta_flow"
DELTA_CHARGE = "delta_charge"
MAX_DELTA = "max_delta"
AVG_DELTA = "avg_delta"
MEDIAN_DELTA = "median_delta"
RELAT_DELTA = "relat_delta"
VA_DEGREE = "va_degree"
INPUT = "input"
OUTPUT = "output"
AGENT_LOG = "agent_log"
RTE_CASE118_EXAMPLE = "rte_case118_example"
EPISODE = "episode"
ORIGIN = "origin"
EXTREMITY = "extremity"
SUB = "substation"
SUB_OR = "substation_origin"
SUB_EX = "substation_extremity"
BRANCH_ATTRIBUTES = [BUS_OR, BUS_EX, SUB_OR, SUB_EX, X_BRANCH, SHIFT_DEGREE, MAX_I_KA, LINE_STATUS]
PROD_ATTRIBUTES = [SUB, PROD, MAX_RAMP_DOWN, MAX_RAMP_UP, PMIN, PMAX, MARGINAL_COST]
LOAD_ATTRIBUTES = [SUB, LOAD]
BRANCH = "Branch"
branch = "branch"
ISOLVER_VARIABLE_LIST += [QUAD_NODE+U1, QUAD_NODE+U2]
TOPO_STATE_ESTIMATION = "topo_state_estimation"
TOPO_DOUBLE = "topo_double"
SUB_CHANGED = "sub_changed"
SUB_ACTIONS = "sub_actions"
ISOLVER_VARIABLE_LIST += [SUB_CHANGED, SUB_ACTIONS]
TOPO_DOUBLE_OPTIM = "topo_double_optim"
SET_BUS = "set_bus"
CHANGE_BUS_VECT = "change_bus_vect"
SET_BUS_VECT = "set_bus_vect"
SUB_OR_S = "sub_or"
SUB_EX_S = "sub_ex"
OBS = "obs"
SOL = "sol"
ACT = "act"
SUB_ID = "sub_id"
CHANGE_BUS = "change_bus"
SOLUTION = "solution"
PTDF_CSV = "ptdf.csv"
GAMEOVER = "gameover"
TIME_STEPS_COMPLETED = "time steps completed"
LINE_OVERFLOW = "line overflow"
ACTIONS_TAKEN = "actions taken"
EP_ = "ep_"
CHECK_LEGALITY = "Check Legality"
FORBIDDEN = "Forbidden"
ETA = "eta"
BUILDER_CONSTRAINT_LIST += [ETA]
GLOBAL_STATE_ESTIMATION = "global_state_estimation"
GLOBAL_SWITCH = "global_switch"
GLOBAL_TOPOLOGY = "global_topology"
GLOBAL_TOPO_ZONE = "global_topology_zone"
GLOBAL_DOUBLE_LEVEL = "global_double_level"
GEN_CARAC_MATCHING = {5: FILENAME_5, 118: FILENAME_118, 14: FILENAME_14}
AGENT = "agent"
SOLVING_TIME = "Solving Time"
RES_CSV = "res.csv"
GLOBAL_ACTION = "global_action"
LOCAL_ACTION = "local_action"
MAX_NUMBER_TIME_STEPS_TO_COMPLETE = "Maximal number of time steps to complete : "
GLOBAL = "global"
LOCAL = "local"
RECONNECTED = "reconnected"
DISCONNECTED = "disconnected"
DISCONNECTED_ID = "disconnected_id"
LINE_BUS_CHANGED = "line_bus_changed"
MODIF_SUB_ID = "modif_subs_id"
FIXED_BRANCHES = "fixed_branches"
FIXED_OR = "fixed_or"
FIXED_EX = "fixed_ex"
FIXED_PRODS = "fixed_prods"
FIXED_LOADS = "fixed_loads"
MODIF_SUB = "modif_sub"
MODIF_BRANCHES = "modif_branches"
NB_BRANCH = "nb_branch"
NB_BUS = "nb_bus"
SHIFT = "shift"
PRODS_CHARAC_CSV = "prods_charac.csv"
UNKNOWN_SOLVER = "Unknown solver"
SOLVER_CHECK_WRONG = "Solver_Check_Wrong"
GRIDVALUECLASS = "gridvalueClass"
#CONSERVATIVE_LIMITS_119 = CONSERVATIVE_LIMITS+"119.npz"
MAX_FLOW_2 = "max_flow_2"
MULTI_ZONES = "multi_zones"
